[package]
name = "pin-project"
version = "0.4.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project/"
keywords = ["pin", "macros", "attribute"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
A crate for safe and ergonomic pin-projection.
"""

[package.metadata.docs.rs]
all-features = true

[workspace]
members = [
    "pin-project-internal",
    "pin-project-internal-impl",
]

[dependencies]
pin-project-internal = { version = "=0.4.1", path = "pin-project-internal", default-features = false }

[dev-dependencies]
compiletest = { version = "=0.3.22", package = "compiletest_rs", features = ["stable", "tmp"] }
