[package]
name = "pin-project-internal-impl"
version = "0.4.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/pin-project"
documentation = "https://docs.rs/pin-project-internal-impl/"
keywords = ["pin", "macros", "attribute"]
categories = ["rust-patterns"]
description = """
An internal crate to support pin_project - do not use directly
"""

[package.metadata.docs.rs]
all-features = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut"] }
